export default {
  ADD_PHOTOS: "ADD_PHOTOS",

  ADD_ALBUMS: "ADD_ALBUMS",
  ADD_ALBUM_CONTENT: "ADD_ALBUM_CONTENT",

  SET_FILES_STATE: "SET_FILES_STATE",
  CLEAR_UPLOAD_FILES: "CLEAR_UPLOAD_FILES",

  SET_VIEWER: "SET_VIEWER",
  SET_PENDING: "SET_PENDING"
};
