export default {
  ADD_PHOTOS: "ADD_PHOTOS",

  SET_ALBUM: "SET_ALBUM",
  ADD_ALBUM_CONTENT: "ADD_ALBUM_CONTENT",

  SET_FILES_STATE: "SET_FILES_STATE",
  CLEAR_UPLOAD_FILES: "CLEAR_UPLOAD_FILES",

  SET_PENDING: "SET_PENDING",

  SET_SELECTION: "SET_SELECTION"
};
